### ISSUE TITLE
Visual Scheduler: changing scheduler bounds start or end issues

### ISSUE THREAD

**Issue by rreganjr** [rreganjr/chichi-ng#52]
The drop zone extends beyond the bounds, the item doesn't get added  because it is OutOfBounds

```
OutOfBounds. The AgendaItem  start=2022-05-21T11:58:00.000-04:00 end=2022-05-21T13:58:00.000-04:00 is out of bounds start=2022-05-20T12:00:00.000-04:00 end=2022-05-21T12:35:00.000-04:00 Error: OutOfBounds. The AgendaItem  start=2022-05-21T11:58:00.000-04:00 end=2022-05-21T13:58:00.000-04:00 is out of bounds start=2022-05-20T12:00:00.000-04:00 end=2022-05-21T12:35:00.000-04:00
    at VisualSchedulerService.addAgendaItem (visual-scheduler.service.ts:278:17)
    at ChannelComponent.onDrop (channel.component.ts:78:36)
    at ChannelComponent_ng_template_0_cc_drop_zone_1_Template_cc_drop_zone_dndDrop_0_listener (channel.component.html:6:20)
    at executeListenerWithErrorHandling (core.mjs:15031:1)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:15069:1)
    at Object.next (Subscriber.js:110:1)
    at SafeSubscriber._next (Subscriber.js:60:1)
    at SafeSubscriber.next (Subscriber.js:31:1)
    at Subject.js:31:1
    at errorContext (errorContext.js:19:1)
```

The OutOfBounds elements in the timeline component don't always get updated.

**Comment by rreganjr** [comment]
Also at the start

The start date is 5-20-2022 12:00 PM, end date is 5/21/2022 12:35PM, the first drop zone of room-2
```
main.js:2286 OutOfBounds. 

The AgendaItem  start=2022-05-20T11:58:00.000-04:00 end=2022-05-20T13:58:00.000-04:00
 is out of bounds start=2022-05-20T12:00:00.000-04:00 end=2022-05-21T12:35:00.000-04:00

 Error: OutOfBounds. 
The AgendaItem  start=2022-05-20T11:58:00.000-04:00 end=2022-05-20T13:58:00.000-04:00
 is out of bounds start=2022-05-20T12:00:00.000-04:00 end=2022-05-21T12:35:00.000-04:00
    at VisualSchedulerService.addAgendaItem (main.js:1546:27)
    at ChannelComponent.onDrop (main.js:2283:42)
    at ChannelComponent_ng_template_0_cc_drop_zone_1_Template_cc_drop_zone_dndDrop_0_listener (main.js:2220:436)
    at executeListenerWithErrorHandling (vendor.js:43760:16)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (vendor.js:43798:22)
    at Object.next (vendor.js:9982:13)
    at SafeSubscriber._next (vendor.js:9932:26)
    at SafeSubscriber.next (vendor.js:9903:18)
    at vendor.js:9754:30
    at errorContext (vendor.js:11820:9)
onDrop @ main.js:2286
```
